name: CICD
on:
  push:
    branches:
      - search-changes
jobs:

  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cicd/tools
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Safe dir
        run: git config --global --add safe.directory /home/runner/work/monorepo-examples/monorepo-examples/
      - name: Run CICD script
        run: python cicd_project.py
